apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: front
spec:
  containers:
    - name: client
      image: elie91/webapp-front
      ports:
        - containerPort: 3000
